<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ошибка</title>
    <link rel="stylesheet" href="/static/css/section/header.css">
    <link rel="stylesheet" href="/static/css/error/error.css">

</head>
<body>

<#include "../section/header.ftlh">

<div class="error-container">
    <h1>Упс</h1>
    <p>Что-то не работает. Попробуйте, пожалуйста, позже :(</p>
</div>
</body>
</html>
